FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
ENV DB_URL="postgresql://postgres:1111@pg_4:5432/dnd_generator"
RUN apt-get update && apt-get install -y python3.9 python3-pip
WORKDIR /hab
COPY ./app .
RUN pip3 install -r requirements.txt
CMD gunicorn --bind 0.0.0.0:8888 app:app
